"""init db

Revision ID: 094b8cf543af
Revises: 
Create Date: 2023-05-18 21:37:07.464499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094b8cf543af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('royalty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('worktime', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_finished', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('one_hour_price', sa.Integer(), sa.Computed('(60 * royalty) / worktime', ), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_projects')
    # ### end Alembic commands ###
