"""drop price

Revision ID: 391acabc084c
Revises: 094b8cf543af
Create Date: 2023-05-18 23:15:40.032005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391acabc084c'
down_revision = '094b8cf543af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_projects', 'one_hour_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_projects', sa.Column('one_hour_price', sa.INTEGER(), sa.Computed('((60 * royalty) / worktime)', persisted=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
