"""new price

Revision ID: 7d20860bd4f2
Revises: 391acabc084c
Create Date: 2023-05-18 23:16:32.462458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d20860bd4f2'
down_revision = '391acabc084c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_projects', sa.Column('one_hour_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_projects', 'one_hour_price')
    # ### end Alembic commands ###
